# Given a properly installed cado-nfs, run cado-nfs in standalone mode that
# uses all the cores available on the machine.
FROM cado-base

COPY 14447_190 single.sh /home/cado/
CMD /home/cado/single.sh /home/cado/14447_190
